### ISSUE TITLE
Suggestion: Show complete list if minMatchingChars = 0

### ISSUE THREAD

**Issue by Meshz** [alexurquhart/vue-bootstrap-typeahead#11]
Hello,

First of all, thank you for this component! It would be nice if we could see the complete list (or the maxMatches if != 0) when the input gets the focus and minMatchingChars = 0.

Thanks for your feedback!

**Comment by alexurquhart** [comment]
Thanks for the suggestion, I'm looking at adding similar functionality soon!

**Comment by Centro1993** [comment]
Would be really nice to have! I was thinking about something like this:
```
    matchedItems() {
      if (this.query.length === 0 && this.minMatchingChars === 0) {
        return this.data.slice(0, this.maxMatches)
      } else if (this.query.length < this.minMatchingChars) {
        return []
      }
```

**Comment by ttodua** [comment]
any news? I cant even made `minMatchingChars` working, it disregards my given number, and always uses `2` .

**Comment by parzibyte** [comment]
> any news? I cant even made `minMatchingChars` working, it disregards my given number, and always uses `2` .

Same here, i had to modify the minified source code (i know this couldn't be the best approach). Just search for `t.maxMatches,minMatchingChars:t.minMatchingChars` and replace with `t.maxMatches,minMatchingChars:1` where **1** is the matching chars you want. It's a dirty fix but it works

**Comment by ttodua** [comment]
> > any news? I cant even made `minMatchingChars` working, it disregards my given number, and always uses `2` .
> 
> Same here, i had to modify the minified source code (i know this couldn't be the best approach). Just search for `t.maxMatches,minMatchingChars:t.minMatchingChars` and replace with `t.maxMatches,minMatchingChars:1` where **1** is the matching chars you want. It's a dirty fix but it works

We just switched to Mattzolinhoffer's forked repo which has been under development during last years
