### ISSUE TITLE
SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by HasnatH** [alexurquhart/vue-bootstrap-typeahead#12]
I have added `vue-bootstrap-typeahead` to my project as follows:

`npm i vue-bootstrap-typeahead --save`

I have other components I am importing such as `vue-bootstrap-datetimepicker` like this:

`import DatePicker from 'vue-bootstrap-datetimepicker'`

However, when I try to import the `vue-bootstrap-typeahead` like this:

`import VueBootstrapTypeahead from 'vue-bootstrap-typeahead'`

I get the following error:

`SyntaxError: Unexpected token <`

I have also tried to use `require` but face the same error:

`var VueBootstrapTypeahead =  require('vue-bootstrap-typeahead')`

I haven't even added it to my `components` or to my `template`

Please advise why I might be having this issue.

Thanks.

**Comment by alexurquhart** [comment]
What does your build chain look like? Are you using vue-cli?

**Comment by HasnatH** [comment]
I am using this project as my base: https://github.com/SimulatedGREG/electron-vue

This is the `main.js` where `Vue` is setup
https://github.com/SimulatedGREG/electron-vue/blob/master/template/src/renderer/main.js

I am trying to import the `vue-bootstrap-typeahead` on a Component vue

I'm not sure what the issue is as other packages are being imported fine in the same Component vue

I've also tried to import in the `main.js` to do `Vue.use()`, however, I get the same unexpected token error as soon as I import

**Comment by alexurquhart** [comment]
I just setup electron-vue and installed the component and got it working without the syntax error. Perhaps upload your .vue file in a gist (along with the console stack trace) or paste it here so we can see what's going on a bit better?

![image](https://user-images.githubusercontent.com/3111563/45164878-5dbba200-b1a8-11e8-8da2-715ea7e3b75b.png)

**Comment by HasnatH** [comment]
Thanks for setting up the project and helping!

I've managed to fix the issue.

For reasons i'm not sure of (yet), I had to explicitly import the Component like this:

`import VueBootstrapTypeahead from 'vue-bootstrap-typeahead/src/components/VueBootstrapTypeahead'`

**Comment by rajesh-gs** [comment]
Sorry to dig up this thread again. I am also facing a similar issue

```
    ERROR in ./node_modules/vue-bootstrap-typeahead/src/components/VueBootstrapTypeahead.vue 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    > <template>
    |   <div>
    |     <div :class="sizeClasses">
     @ ./ClientApp/views/home.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./ClientApp/views/home.vue?vue&type=script&lang=js&) 2:0-97 35:27-48
     @ ./ClientApp/views/home.vue?vue&type=script&lang=js&
     @ ./ClientApp/views/home.vue
     @ ./ClientApp/router/routes.js
     @ ./ClientApp/router/index.js
     @ ./ClientApp/boot-app.js

```
I tried to provide full import path like @HasnatH 's but it still fails. 
I am running
     "vue": "2.5.16",
     "vue-loader": "15.4.2",
    "webpack": "^4.28.2",
    "webpack-cli": "3.1.2",
    "bootstrap-vue": "^2.0.0-rc.11",
    "vue-bootstrap-typeahead": "^0.2.6",
    "@babel/core": "7.2.2",
    "@babel/plugin-syntax-dynamic-import": "^7.2.0",
    "@babel/plugin-transform-runtime": "7.2.0",
    "@babel/preset-env": "7.2.3",
    "@babel/runtime": "7.2.0",

**Comment by BloodSucker123** [comment]
Still not working. Also I use @HasnatH but still its not working instead it says `Module not found`

**Comment by danielbonifacio** [comment]
I was getting the same error using nuxt in `universal` mode.

I solved creating a nuxt plugin with ssr disabled:

``` js
// plugins/autocomplete.js
import Vue from 'vue'
import VueBootstrapTypeahead from 'vue-bootstrap-typeahead'

Vue.component('v-autocomplete', VueBootstrapTypeahead)
```

``` js
// nuxt.config.js
{
  plugins: [
    { src: '~/plugins/autocomplete', ssr: false }
  ]
}
```
Idk why it happens, but apparently this solve the problem.

**Comment by kangchals** [comment]
For me, it happens when page is reloaded. ( I am using nuxt too )
hmm...

**Comment by zyriu** [comment]
@danielbonifacio 
Your solution does work, but please mind that there is a typo in your code, it's vue-bootstrap-typeAhead, not vue-bootstrap-typehead.
Otherwise, thank you for solving a major headache ;)

**Comment by tettoffensive** [comment]
@danielbonifacio Does adding ssr false just mean the component won't show up when the server renders the component?

**Comment by danielbonifacio** [comment]
@tettoffensive It means that the component will be rendered only on the client-side. Nuxt will only have a reference to where it should be on the template, but will not mount or execute it. That's because a server rendering does not have some APIs, like `document`. They're available on the browser.

**Comment by pdpotter** [comment]
I managed to get the [vue-typeahead-bootstrap](https://github.com/mattzollinhofer/vue-typeahead-bootstrap) component to render server side as well in a nuxt application by configuring the vue-typeahead-bootstrap component to be [transpiled in nuxt.config.js](https://nuxtjs.org/api/configuration-build/#transpile):

```
{
  build: {
    transpile: [
      ({ isServer }) => 'vue-typeahead-bootstrap'
    ]
  }
}
```
