### ISSUE TITLE
Results on top?

### ISSUE THREAD

**Issue by dunderrrrrr** [alexurquhart/vue-bootstrap-typeahead#17]
Is there a way to make the results appear above the searchfield? I fiddled around and manage to set ``margin-top: -120px;``  to the  class `.vbt-autcomplete-list[data-v-9a21a6f4]`. 

But how do I bind it? I have multiple searchfields on the same page and I would like this to only be set on one autocomplete-list.

**Comment by dunderrrrrr** [comment]
Ah, I solved it.

```
div.yourothersearchfield .vbt-autcomplete-list {
    margin-top:-100px;
}
```

Is this the correct way of doing it, or is there another way?

**Comment by dunderrrrrr** [comment]
However...

Seems like if the `.vbt-autcomplete-list` is big, multiple results, it covers the searchfield. So this is not a very good solution.

Suggestions?

**Comment by alexurquhart** [comment]
I have a feeling you will have to modify the position of the autocomplete list every time the size/content changes. I already use [resize observer](https://developers.google.com/web/updates/2016/10/resizeobserver) to modify the width of the list based on the width of the input, you might be able to do the same for the vertical position.
