### ISSUE TITLE
Slot for suggestion formatting

### ISSUE THREAD

**Issue by Owumaro** [alexurquhart/vue-bootstrap-typeahead#5]
First of all, thanks for this plugin. I tried pretty much every other "vue-autocomplete" plugin and didn't find any as clean and customizable as this one. :+1: 

I'm trying to replace "seamlessly" google maps autocomplete with this plugin, therefore I need to achieve this UI:

![image](https://user-images.githubusercontent.com/5205295/44844165-724ce700-ac4a-11e8-894d-3f46aa9bf055.png)

As you can see the template is something like:

```html
<font-awesome-icon icon="map-marker-alt" /> {{ suggestion.name }} <small>{{ suggestion.countryName }}</small>
```

However formatting is only customisable by the `serializer` property which requires a function.

It would be nice to be able to use a scoped slot (see [vue scoped slots](https://fr.vuejs.org/v2/guide/components-slots.html#Scoped-Slots)).

I will try to submit a PR when I have time.

**Comment by alexurquhart** [comment]
Thanks for the suggestion, this functionality was definitely something I had in mind and I would happily accept a PR for this.
