### ISSUE TITLE
Autofocus when component mounted or after refresh page

### ISSUE THREAD

**Issue by jamalapriadi** [alexurquhart/vue-bootstrap-typeahead#64]
how to add aotufocus to component vue-bootstrap-typeahead when the component in mounted or after refresh the page. Thanks

**Comment by firibz** [comment]
I have same problem

**Comment by mattzollinhofer** [comment]
This repo isn't maintained any longer, but I'm actively maintaining a fork here: https://github.com/mattzollinhofer/vue-typeahead-bootstrap

My initial reaction is to say that this component won't attempt to "grab" focus after it's mounted or the page is loaded. You could set the page's focus to this typeahead your component (where you use this typeahead) has mounted though. Hope that helps!
